# Generated by Django 4.0.4 on 2023-11-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studenModel',
            new_name='studentModel',
        ),
    ]
